name: Build on commit
on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add more swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8

      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Test glxinfo
        run: |
          sudo apt-get install -y mesa-utils xvfb
          xvfb-run glxinfo

      - name: Build OPENRNDR
        run: xvfb-run ./gradlew build