name: Release to Bintray
on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
      - v[0-9].[0-9]+.[0-9]+-rc.[0-9]+
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build and publish to local maven
        run: ./gradlew -Prelease.useLastTag=true candidate publishToMavenLocal --info
      - name: Zip and publish to Bintray
        run: |
          cd ~/.m2/repository
          zip release.zip org/openrndr/openrndr*/${{ steps.get_version.outputs.VERSION }}/*
          curl -u ${{ secrets.BINTRAY_USER }}:${{ secrets.BINTRAY_KEY }} -X PUT https://api.bintray.com/content/openrndr/openrndr/ \
            -H "X-Bintray-Package:openrndr" \
            -H "X-Bintray-Version:${{ steps.get_version.outputs.VERSION }}" \
            -H "X-Bintray-Publish:1" \
            -H "X-Bintray-Override:1" \
            -H "X-Bintray-Explode:1" \
            -T release.zip